export const SKILLS = [
    {
        "count":"Tema",
        "title":"Redes",
        "description":"Contamos con una comprensión sólida de las redes y podemos aplicar sus fundamentos para analizar, diseñar y conectar dispositivos de forma eficiente. Nuestra experiencia en este tema está completamente consolidada.",
        "percentage":100,
        "status":true,
    },
    {
        "count":"Tema",
        "title":"Clasificación de redes",
        "description":"Reconocemos y diferenciamos las principales clasificaciones de redes según su alcance, topología y propósito. Podemos seleccionar la alternativa más adecuada para cada escenario con seguridad y criterio técnico.",
        "percentage":100,
        "status":true,
    },
    {
        "count":"Tema",
        "title":"Configuración de switches",
        "description":"Tenemos experiencia configurando switches, asignando parámetros básicos y verificando la comunicación entre dispositivos. Podemos resolver las tareas habituales de una red con autonomía.",
        "percentage":100,
        "status":true,
    },
    {
        "count":"Tema",
        "title":"Protocolos de red",
        "description":"Comprendemos el propósito y funcionamiento de los principales protocolos de red, y podemos relacionarlos con situaciones prácticas de comunicación. Aún estamos fortaleciendo algunos casos especializados para alcanzar un dominio completo.",
        "percentage":90,
        "status":false,
    },
    {
        "count":"Tema",
        "title":"Modelo OSI",
        "description":"Identificamos las siete capas del modelo OSI y su función dentro de la comunicación de datos. Podemos explicar su estructura y aplicarla en análisis básicos, mientras continuamos profundizando en la interacción entre capas.",
        "percentage":70,
        "status":false,
    },
    {
        "count":"Tema",
        "title":"Protocolos TCP/IP",
        "description":"Manejamos los conceptos esenciales de TCP/IP y podemos explicar cómo se organizan sus protocolos para permitir la comunicación en Internet. Nuestra experiencia es avanzada, aunque seguimos practicando escenarios de configuración y diagnóstico más complejos.",
        "percentage":90,
        "status":false,
    },
    {
        "count":"Tema",
        "title":"Capa Física",
        "description":"Comprendemos cómo se transmiten los bits por el medio físico y cómo influyen los cables, conectores, señales y velocidades. Podemos aplicar estos fundamentos con confianza en la revisión de una conexión de red.",
        "percentage":100,
        "status":true,
    },
    {
        "count":"Tema",
        "title":"Capa de Enlace de Datos",
        "description":"Comprendemos el funcionamiento de la capa de enlace de datos, incluyendo tramas, direcciones MAC y control del acceso al medio. Podemos relacionar estos conceptos con la comunicación entre dispositivos dentro de una red local.",
        "percentage":100,
        "status":true,
    },
    {
        "count":"Tema",
        "title":"Capa de red",
        "description":"Reconocemos la función de la capa de red y el papel del direccionamiento IP en la entrega de paquetes. Podemos describir su funcionamiento y resolver ejercicios básicos, mientras continuamos adquiriendo experiencia práctica.",
        "percentage":60,
        "status":false,
    }
]